### PR TITLE
Bug/stop when unreachable

### LINKED ISSUE #41: Grabber should fail to start if the provided host in unreachable?
It seems like when turning on the grabber, and the host is unreachable, the grabber should be turned back off and convey to the user that the provided host is unreachable.

Any thoughts on this from anyone? Seems like the right move to me, though we may need to look at how this interacts with the reconnect behavior (maybe not).

### PR DESCRIPTION
**Pull request by abrenoch**
Fixes #41

### CODE REVIEW

**Comment by abrenoch** [comment]
New commits fixed some problems that likely came from a recent merge, and also slipped in a resolution for #25

File: common/src/main/java/com/abrenoch/hyperiongrabber/common/HyperionScreenService.java [hunk 1]
```diff
@@ -186,6 +194,12 @@ public void onDestroy() {
         super.onDestroy();
     }
 
+    private void haltStartup() {
+        // this line feels unnecessary, but problems happen without it
```
Comment (ninovanhooff) [inline common/src/main/java/com/abrenoch/hyperiongrabber/common/HyperionScreenService.java]: This is because the service will be killed otherwise, right? That's a valid reason to put it here

File: common/src/main/java/com/abrenoch/hyperiongrabber/common/HyperionScreenService.java [hunk 2]
```diff
@@ -42,6 +42,7 @@
 
     private boolean OGL_GRABBER = false;
     private boolean RECONNECT = false;
+    private boolean HAS_CONNECTED = false;
```
Comment (ninovanhooff) [inline common/src/main/java/com/abrenoch/hyperiongrabber/common/HyperionScreenService.java]: only constants should be in caps.  this should be named `hasConnected`

File: common/src/main/java/com/abrenoch/hyperiongrabber/common/HyperionScreenService.java (hunk 1 above)
Comment (ninovanhooff) [inline common/src/main/java/com/abrenoch/hyperiongrabber/common/HyperionScreenService.java]: Preventing the service from being killed is a valid reason to use it
